rootProject.name = "StockFly"
include(":app")
include(":core-model")
include(":core-common")
include(":core-ui")
include(":core-formatter")
include(":core-utils")
include(":core-customtabs")
include(":core-network")
include(":core-database")
include(":core-preferences")
include(":core-work")
include(":core-data")
include(":core-buildconfig")
include(":core-shortcuts")
include(":core-navigation")
