object Versions {

    const val kotlin = "1.6.21"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.4.1"
    const val constraint = "2.1.3"
    const val recyclerView = "1.2.1"
    const val fragmentKtx = "1.4.1"
    const val material = "1.6.0"
    const val lifecycle = "2.4.1"
    const val archLfecycleExt = "1.1.1"
    const val coroutines = "1.6.1"
    const val room = "2.4.2"
    const val hilt = "2.42"
    const val hiltCompiler = "1.0.0"
    const val hiltWorkManager = "1.0.0"
    const val moshi = "1.13.0"
    const val retrofit = "2.9.0"
    const val coil = "2.0.0"
    const val timber = "5.0.1"
    const val okhttp = "4.9.3"
    const val leakCanary = "2.9.1"
    const val asynclayoutinflater = "1.0.0"
    const val browser = "1.4.0"
    const val workManager = "2.7.1"
}